name: kudal_diet
description: 쿠달이 - 캐릭터 기반 다이어트 기록 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  table_calendar: ^3.1.2
  fl_chart: ^0.69.0
  intl: ^0.19.0
  flutter_riverpod: ^2.5.1
  dio: ^5.4.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
